### ISSUE TITLE
执行转账一直报PIN incorrect.

### ISSUE THREAD

**Issue by hanorz** [wenewzhang/mixin_labs-python-bot#13]
执行转账一直报PIN incorrect.
之前一直没问题，最近才出现的问题，pin码确定没错。
n 3.6.5 :: Anaconda, Inc.

**Comment by wenewzhang** [comment]
Pin incorrect有两种情况：
1.的确不对
2.对的，但访问的迭代器不一样，比如你在go里访问过，一切正常！但切换到python再去访问，这时迭代器不一样了，就会提示PIN incorrect
还有一种情况，如果你访问5次还不正确，系统会将这个帐号锁定24小时，等24小时后再试，否则会一直提示PIN incorrect!
