### ISSUE TITLE
http://freemixinapptoken.myrual.me/token is unreachable

### ISSUE THREAD

**Issue by harryisfish** [wenewzhang/mixin_labs-python-bot#16]
When I try to generate a Mixin User, Traceback told me that "http://freemixinapptoken.myrual.me/token" made a ConnectionError.

At the same time I try to check this url on Chrome, the "ERR_NAME_RESOLUTION_FAILED" was shown on the screen.

Is that url necessary for generate a Mixin User? If so, what can I do now?

**Comment by harryisfish** [comment]
I read the doc of Mixin knowing that I have to generate a ACCESS_TOKEN for the new user. Is it equal to the thing I will get from "http://freemixinapptoken.myrual.me/token" when this web was working?

**Comment by wenewzhang** [comment]
First, Apply a develop account from mixin.one! then create the user by youself,
https://github.com/wenewzhang/mixin_labs-python-bot/blob/master/call_apis.py#L124

**Comment by Tymon42** [comment]
Thank you! I creater a User successfully with the method you provide.  Does that mean I don't need to request  "http://freemixinapptoken.myrual.me/token" ?

**Comment by harryisfish** [comment]
Thank you! I creater a User successfully with the method you provide. Does that mean I don't need to request "http://freemixinapptoken.myrual.me/token" any more?

**Comment by wenewzhang** [comment]
yes, http://freemixinapptoken.myrual.me/token do the same thing as above two step!
